### PR TITLE
objstore: adding minTimestamp, maxTimestamp options.

### PR DESCRIPTION
**Pull request by sravotto**
This change allows user to specify a range of resolved timestamp to replay the events stored in a cloud provider storage bucket. It also adds support for additional authentication methods for AWS.

To support this change, we introduced  a types.MutationFilter function.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/939)

### CODE REVIEW

**Review by bobvawter — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/939)* status: 0 of 10 files reviewed, 17 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`internal/source/objstore/config.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B4zIb-gBv1cEMj_3p:-O2B4zIc0GXOALMVmKDI:b2ly2a7) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L92)):*
> ```Go
> 	BufferSize           int
> 	FetchDelay           time.Duration
> 	MaxTimestamp         string
> ```

Should this be a `time.Time` ?
___
*[`internal/source/objstore/config.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B4e7r3POAkypAVstZ:-O2B4e7r3POAkypAVst_:b-7e6p0z) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L94)):*
> ```Go
> 	MaxTimestamp         string
> 	MinTimestamp         string
> 	PartitionFormat      string
> ```

This should be an enum type. If the type implements https://pkg.go.dev/github.com/spf13/pflag#Value, then the field can be used directly with https://pkg.go.dev/github.com/spf13/pflag#Var
___
*[`internal/source/objstore/config.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B14qc4jCZFX_Ms3Iq:-O2B14qd5Uyp6fYQr5C6:bvo2a4m) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L95)):*
> ```Go
> 	MinTimestamp         string
> 	PartitionFormat      string
> 	ResolvedInterval     time.Duration // Minimal duration between resolved timestamps.
> ```

Is this `PollingInterval` ?
___
*[`internal/source/objstore/config.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B5UYZ5Tzh3-HdqGbU:-O2B5UYZ5Tzh3-HdqGbV:b-4qn30m) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L126)):*
> ```Go
> 		"time to wait between fetching the list of entries in a bucket")
> 	f.StringVar(&c.MaxTimestamp, "maxTimestamp", "",
> 		"only accept messages older than this timestamp; this is an exclusive upper limit")
> ```

Is this a human-readable timestamp? HLC time?
___
*[`internal/source/objstore/config.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B5ApBCvNblw8dPiBV:-O2B5ApBCvNblw8dPiBW:b1c5mow) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L130)):*
> ```Go
> 		"only accept unprocessed messages at or newer than this timestamp; this is an inclusive lower limit")
> 	f.StringVar(&c.PartitionFormat, "partitionFormat", "daily",
> 		"how changefeed file paths are partitioned: daily, hourly, flat")
> ```

Extract to constants.
___
*[`internal/source/objstore/config.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B5D0N9Xl8x_s-CFtm:-O2B5D0N9Xl8x_s-CFtn:b-c38l4b) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L131)):*
> ```Go
> 	f.StringVar(&c.PartitionFormat, "partitionFormat", "daily",
> 		"how changefeed file paths are partitioned: daily, hourly, flat")
> 	f.DurationVar(&c.ResolvedInterval, "resolvedInterval", 5*time.Second, `interval between two resolved timestamps.
> ```

Should the 5 seconds be a constant and also initialized in `Preflight()`?
___
*[`internal/source/objstore/conn.go` line 223 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B8WFc9bHxdGSkQxmv:-O2B8WFc9bHxdGSkQxmw:bcpuyyf) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L223)):*
> ```Go
> }
> 
> func (c *Conn) checkValidRange(ctx *stopper.Context, res *resolvedRange) (bool, error) {
> ```

What are the attributes of a valid range?
___
*[`internal/source/objstore/conn.go` line 240 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B7wCwBkYm-CielmbY:-O2B7wCwBkYm-CielmbZ:b91d3yi) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L240)):*
> getResolvedTimestamp retrieves a resolved timestamp message located at the given path.
___
*[`internal/source/objstore/conn.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B86mF0QxCiiMoVoZM:-O2B86mF0QxCiiMoVoZN:b-54p30b) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L252)):*
> ```Go
> 	}
> 	defer buff.Close()
> 	return c.parser.Resolved(buff)
> ```

It would be useful to include the path if the parsing fails, since that would indicate bad data was uploaded to the bucket.
___
*[`internal/source/objstore/conn.go` line 255 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B6HDy0J4QeE1Ucikd:-O2B6HDy0J4QeE1Ucike:bkujz20) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L255)):*
> filePrefix returns a path within the connection's bucket based on the configured partition file format.
___
*[`internal/source/objstore/conn.go` line 258 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B6ySX7Fr72Rj1a8hS:-O2B6ySX7Fr72Rj1a8hT:b-64doxb) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L258)):*
> ```Go
> func (c *Conn) filePrefix(dir string, timestamp time.Time) (string, error) {
> 	switch c.config.PartitionFormat {
> 	case "daily":
> ```

Using literals in case statements creates maintenance problems later on.
___
*[`internal/source/objstore/conn.go` line 282 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B9lgQ750pv3e_UalY:-O2B9lgQ750pv3e_UalZ:b-hz4gg6) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L282)):*
> ```Go
> 		return "", nil
> 	}
> 	veryFirst, err := c.findResolved(ctx, dir, "", true)
> ```

`earliestResolved`
___
*[`internal/source/objstore/conn.go` line 288 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B8knU61nb7A5huuSz:-O2B8knU61nb7A5huuT-:b2opphd) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L288)):*
> ```Go
> 	// nothing found in the bucket.
> 	if veryFirst.to == "" {
> 		return "", nil
> ```

Returning the zero value as a does-not-exist sentinel isn't idiomatic. Add an `ok` return value to the method.
___
*[`internal/source/objstore/conn.go` line 295 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B9EItCNuaJYh6rG0w:-O2B9EItCNuaJYh6rG0x:bkwqrfd) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L295)):*
> ```Go
> 		from, err := c.filePrefix(dir, min)
> 		if err != nil {
> 			log.WithField("bucket", c.config.bucketName).
> ```

In general, use `log.WithError()` to capture the object.
___
*[`internal/source/objstore/conn.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2BAdm0EH6eNC-_VWFS:-O2BAdm0EH6eNC-_VWFT:b-6na5o0) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L320)):*
> ```Go
> 		}
> 		// go back and try again.
> 		min = min.Add(-c.config.ResolvedInterval)
> ```

If the changefeed had been down for an extended period of time, couldn't this result in an arbitrarily large number of requests to the bucket?
___
*[`internal/source/objstore/providers/s3/s3.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2BBbFh8hOxG61W-DLp:-O2BBbFh8hOxG61W-DLq:b4zc3do) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/providers/s3/s3.go#L65)):*
> ```Go
> 	Insecure     bool   // For testing against self hosted S3 providers.
> 	SecretKey    string // Secret associated to the Access Key
> 	SessionToken string // Session token
> ```

Where is this assigned to?
___
*[`internal/types/types.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2BBfZs0Rl2y_RUGLsS:-O2BBfZs0Rl2y_RUGLsT:bnu3lcf) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/types/types.go#L148)):*
> ```Go
> 
> // MutationFilter check if a mutation satisfies a condition.
> type MutationFilter func(Mutation) bool
> ```

This is a predicate.

**Review by sravotto — COMMENTED** [review]
Please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/939#-:-O2Py2cODSS_gPW4lNCK:b1xog4q)* status: 0 of 12 files reviewed, 17 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`internal/source/objstore/config.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B4zIb-gBv1cEMj_3p:-O2PrFzi38xn2HbLbEWH:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L92)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Should this be a `time.Time` ?
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B4e7r3POAkypAVstZ:-O2PrHgZ7k4_tKede4Kn:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L94)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This should be an enum type. If the type implements https://pkg.go.dev/github.com/spf13/pflag#Value, then the field can be used directly with https://pkg.go.dev/github.com/spf13/pflag#Var
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B14qc4jCZFX_Ms3Iq:-O2PrIj1-S4YRJ8U0BYp:bsazltd) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L95)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is this `PollingInterval` ?
</blockquote></details>

not quite - it's how often the changefeed emits resolved timestamps. It's used to as a hint to find resolved timestamp files, in case we specify a min resolved timestamp.
___
*[`internal/source/objstore/config.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B5UYZ5Tzh3-HdqGbU:-O2Pri4ZDxtdy2PPDUKC:b-q73qxc) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L126)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is this a human-readable timestamp? HLC time?
</blockquote></details>

Done. I implemented the `pflag.Value` interface for `hlc.Time`.
___
*[`internal/source/objstore/config.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B5ApBCvNblw8dPiBV:-O2Prxaa-HIKJdgzjnWj:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L130)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Extract to constants.
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B5D0N9Xl8x_s-CFtm:-O2Pry3W81G2kjp-cXm9:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L131)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Should the 5 seconds be a constant and also initialized in `Preflight()`?
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 223 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B8WFc9bHxdGSkQxmv:-O2Przyg2hPM7E1sKMFJ:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L223)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

What are the attributes of a valid range?
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 240 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B7wCwBkYm-CielmbY:-O2Ps-m0EIyXL0hFBO_c:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L240)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

> getResolvedTimestamp retrieves a resolved timestamp message located at the given path.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B86mF0QxCiiMoVoZM:-O2Ps0kV8nwZFUDoND0G:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L252)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

It would be useful to include the path if the parsing fails, since that would indicate bad data was uploaded to the bucket.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 255 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B6HDy0J4QeE1Ucikd:-O2PwNy10P6HzEGJa7_Q:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L255)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

> filePrefix returns a path within the connection's bucket based on the configured partition file format.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 258 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B6ySX7Fr72Rj1a8hS:-O2PsMMf8srTKnbi0GsY:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L258)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Using literals in case statements creates maintenance problems later on.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 282 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B9lgQ750pv3e_UalY:-O2PsNSl5s51BnQtOwRu:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L282)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`earliestResolved`
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 288 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B8knU61nb7A5huuSz:-O2PsOZcDvpEhgKwaSOJ:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L288)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Returning the zero value as a does-not-exist sentinel isn't idiomatic. Add an `ok` return value to the method.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 295 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B9EItCNuaJYh6rG0w:-O2PsP4621ztA4gqTrqZ:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L295)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

In general, use `log.WithError()` to capture the object.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2BAdm0EH6eNC-_VWFS:-O2PsQ1H6QnLvBphnvuK:bncyytp) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L320)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

If the changefeed had been down for an extended period of time, couldn't this result in an arbitrarily large number of requests to the bucket?
</blockquote></details>

That's possible. we might have to scan several file names to find a resolved timestamp.
___
*[`internal/source/objstore/providers/s3/s3.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2BBbFh8hOxG61W-DLp:-O2PsjQhBNRffLRYC1d5:b-zplpb) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/providers/s3/s3.go#L65)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Where is this assigned to?
</blockquote></details>

This is used mostly in in our testing env where we have short term credentials. 
Also, I changed the s3 provider to use additional authentication methods,  including implicit iam roles (simply leveraging the underlying library capability)
___
*[`internal/types/types.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2BBfZs0Rl2y_RUGLsS:-O2PtDlM9BSlRCCzfAFV:byjxfsa) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/types/types.go#L148)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This is a predicate.
</blockquote></details>

Done. Did you refer to the comment? Or something else?

**Review by bobvawter — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/939)* status: 4 of 12 files reviewed, 4 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`internal/source/objstore/config.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B14qc4jCZFX_Ms3Iq:-O2_-u3E8eW5JsdRfBH_:bbtiked) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L95)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

not quite - it's how often the changefeed emits resolved timestamps. It's used to as a hint to find resolved timestamp files, in case we specify a min resolved timestamp.
</blockquote></details>

Call this `ResolvedSeekInterval`, then and have the comment refer to the help text below.
___
*[`internal/source/objstore/config.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B5UYZ5Tzh3-HdqGbU:-O2_12jmDfBfVEXGGhyd:bniwyqv) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L126)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Done. I implemented the `pflag.Value` interface for `hlc.Time`.
</blockquote></details>

The help strings for these flags should clarify that it's an HLC timestamp.
___
*[`internal/source/objstore/config.go` line 93 at r2](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2_-ODe5avL_6TfkfUO:-O2_-ODe5avL_6TfkfUP:bg3kmnu) ([raw file](https://github.com/cockroachdb/replicator/blob/e02b63f4de53cf7294298008af24d2c2523891df/internal/source/objstore/config.go#L93)):*
> ```Go
> // Set implements pflag.Value
> func (p *PartitionFormat) Set(value string) error {
> 	log.Warnf("PartitionFormat %s", value)
> ```

Remove log statement here.
___
*[`internal/source/objstore/conn.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2BAdm0EH6eNC-_VWFS:-O2_72BNEwK5hMe7ASbS:b-15efwx) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L320)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

That's possible. we might have to scan several file names to find a resolved timestamp.
</blockquote></details>

I'm concerned about the total number of API requests that would retrieve the same object, given the reverse-scanning behavior in `findStartingResolved` and the lack of an upper bound in the `ListObjects` S3 API.  If the reverse-scanning interval is 1s and the previous resolved timestamp was an hour ago, aren't you're looking at 1440 mostly-redundant calls out to the bucket?  I think you're better off doing a forward-walk over the object keys within the smallest time bound possible or to ideally perform a binary search over the key space.  Given a pivot point, list objects in a forward direction until you find a resolved timestamp, then select a partition.

**Review by sravotto — COMMENTED** [review]
please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/939#-:-O2aCw1GAzbQamanfD9t:b-vwkhti)* status: 3 of 13 files reviewed, 4 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`internal/source/objstore/config.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B14qc4jCZFX_Ms3Iq:-O2aCQ5Y5gKeGnLLJnfy:brpmqc3) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L95)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Call this `ResolvedSeekInterval`, then and have the comment refer to the help text below.
</blockquote></details>

removed.
___
*[`internal/source/objstore/config.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2B5UYZ5Tzh3-HdqGbU:-O2aCU9h5_mEeb8nJ7Nm:b-7rl0jd) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/config.go#L126)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

The help strings for these flags should clarify that it's an HLC timestamp.
</blockquote></details>

done.
___
*[`internal/source/objstore/config.go` line 93 at r2](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2_-ODe5avL_6TfkfUO:-O2aCOpm6KaWJz3VPfzt:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/e02b63f4de53cf7294298008af24d2c2523891df/internal/source/objstore/config.go#L93)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Remove log statement here.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2BAdm0EH6eNC-_VWFS:-O2aCYTG4InSiT9VPBPB:bdaihyl) ([raw file](https://github.com/cockroachdb/replicator/blob/5961242c6417ffb662586ceae39f6ab81e574a82/internal/source/objstore/conn.go#L320)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I'm concerned about the total number of API requests that would retrieve the same object, given the reverse-scanning behavior in `findStartingResolved` and the lack of an upper bound in the `ListObjects` S3 API.  If the reverse-scanning interval is 1s and the previous resolved timestamp was an hour ago, aren't you're looking at 1440 mostly-redundant calls out to the bucket?  I think you're better off doing a forward-walk over the object keys within the smallest time bound possible or to ideally perform a binary search over the key space.  Given a pivot point, list objects in a forward direction until you find a resolved timestamp, then select a partition.
</blockquote></details>

ok - as discussed, we will start processing files that are after the minTimestamp provided, without seeking a resolved timestamp file.

**Review by bobvawter — APPROVED** [review]
:lgtm: w/ nit

> Reviewed 3 of 10 files at r1, 3 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/939#-:-O2eAEog4w44pWCR5p4j:b-uobk8w)* status: all files reviewed, 1 unresolved discussion (waiting on @BramGruneir and @sravotto)

___
*[`internal/source/objstore/config.go` line 79 at r3](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2e7bHr7puVKrspFBfO:-O2e7bHs0CtSnZcwN9-X:b-bvn2i8) ([raw file](https://github.com/cockroachdb/replicator/blob/f3f2fc50627a1e948d6f720766169d66ebbbffa0/internal/source/objstore/config.go#L79)):*
> ```Go
> // PartitionFormats returns the available partition formats.
> func PartitionFormats() []string {
> 	res := make([]string, 0)
> ```

It's more idiomatic to write `var res []string` than to allocate a zero-length slice.  The optimization here would be to have a non-exported symbol that comes after `Hourly`. This would allow you to allocate a slice with exactly the correct length.

**Review by sravotto — COMMENTED** [review]
thank you.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/939#-:-O2eNl5Q9lsAfecF7fbk:bsv417u)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @bobvawter and @BramGruneir)

___
*[`internal/source/objstore/config.go` line 79 at r3](https://reviewable.io/reviews/cockroachdb/replicator/939#-O2e7bHr7puVKrspFBfO:-O2eNjxU0L58ivdL0N6W:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/f3f2fc50627a1e948d6f720766169d66ebbbffa0/internal/source/objstore/config.go#L79)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

It's more idiomatic to write `var res []string` than to allocate a zero-length slice.  The optimization here would be to have a non-exported symbol that comes after `Hourly`. This would allow you to allocate a slice with exactly the correct length.
</blockquote></details>

Done.

**Pull request merged**
