### PR TITLE
.vscode: added in debugger and testdata setup for VSCode

### PR DESCRIPTION
**Pull request by ryanluu12345**
As part of my learning of replicator, I wanted to step through all of the code an life of mutations, so I went ahead and created some starter VSCode debugger configurations that can better help folks who want to onboard with VSCode. I'll gitignore these and share these files via zip file in Google drive.

Also aded a testdata directory that is gitignored since I have local testdata I want to use for my local testing but I don't want to check these into the repo.

Release Note: None

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1029)

### CODE REVIEW

**Comment by bobvawter** [comment]
IDE configurations shouldn't be checked in.  The `testdata/` change is reasonable.

**Review by bobvawter — APPROVED** [review]
LGTM

**Comment by bobvawter** [comment]
Since this doesn't touch anything that triggers the tests: https://github.com/cockroachdb/replicator/wiki/Contributing#workflow-status-bypass

**Comment by ryanluu12345** [comment]
> Since this doesn't touch anything that triggers the tests: https://github.com/cockroachdb/replicator/wiki/Contributing#workflow-status-bypass

Thanks for the tip! Just did this and adding to merge queue now.

**Pull request merged**
