### PR TITLE
kafka: adding best effort and consistent mode.

### PR DESCRIPTION
**Pull request by sravotto**
This change adds transactional support to the Kafka connector for changefeeds.
    
This change uses the conveyor package to deliver mutation to the target database in any of the supported modes of operations.
    
The conveyor tracks resolved timestamps across all the partitions with a topic, and ensures that the checkpoint used by cdc-sink is advanced  based on the minimal resolved timestamp received on all the partitions.

A second commit, refactors the configuration for better readability.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/843)

### CODE REVIEW

**Review by bobvawter — COMMENTED** [review]
> Reviewed 1 of 6 files at r3, 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/843)* status: all files reviewed, 6 unresolved discussions (waiting on @BramGruneir and @sravotto)

___
*[`internal/source/kafka/consumer.go` line 47 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYgkneEcrzGufwQe1Z:-NxYgknf3gUUkHwAVZoO:brsq8f1) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/consumer.go#L47)):*
> ```Go
> 	schema    ident.Schema      // The target schema.
> 	timeRange hlc.Range         // The time range for incoming mutations.
> 	fromState []*partitionState // The initial offsets for each partitions.
> ```

Sort order.
___
*[`internal/source/kafka/consumer.go` line 69 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYgrkZ1y5sjmHEM35u:-NxYgrkZ1y5sjmHEM35v:bx4zkwb) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/consumer.go#L69)):*
> ```Go
> 		session.MarkOffset(marker.topic, marker.partition, marker.offset, "start")
> 	}
> 	c.mu.done = make(map[string]bool)
> ```

Not knowing how `Setup` is called, and from which goroutine(s), you should go ahead and lock the mutex to avoid any surprises later on.
___
*[`internal/source/kafka/consumer.go` line 110 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYhD_R8YcUkM3IA_j1:-NxYhD_R8YcUkM3IA_j2:bahgtvq) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/consumer.go#L110)):*
> ```Go
> 			payload, err := c.accumulate(toProcess, message)
> 			if err != nil {
> 				log.Error(err)
> ```

Use `log.WithError(err).Error("message")` Otherwise, the error object isn't going to be presented to the logging hooks as an `error` object.
___
*[`internal/source/kafka/injector.go` line 27 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYhjxz9urGFVEffgO8:-NxYhjxz9urGFVEffgO9:bpjeyqo) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/injector.go#L27)):*
> ```Go
> 	"github.com/cockroachdb/replicator/internal/conveyor"
> 	scriptRuntime "github.com/cockroachdb/replicator/internal/script"
> 	"github.com/cockroachdb/replicator/internal/sequencer/retire"
> ```

Did you run `crlfmt`?  I think you'd get a code-quality warning if the imports aren't sorted.

`go run github.com/cockroachdb/crlfmt -w -ignore _gen.go .`
___
*[`internal/source/kafka/injector.go` line 53 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYhf1R-S-fHYSVCvTP:-NxYhf1R-S-fHYSVCvTQ:b-suv37y) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/injector.go#L53)):*
> ```Go
> 		tgt.Set,
> 		retire.Set,
> 		conveyor.Set,
> ```

Alphabetize.
___
*[`internal/source/kafka/provider.go` line 30 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYi0aW4arZJD9M5MpQ:-NxYi0aW4arZJD9M5MpR:b-80xfat) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/provider.go#L30)):*
> ```Go
> 	ProvideConn,
> 	ProvideEagerConfig,
> 	ProvideConveyorConfig,
> ```

Sort.

**Review by sravotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/843)* status: 10 of 13 files reviewed, 6 unresolved discussions (waiting on @bobvawter and @BramGruneir)

___
*[`internal/source/kafka/consumer.go` line 47 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYgkneEcrzGufwQe1Z:-NxwfzUB-6lgjF8H4Erk:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/consumer.go#L47)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort order.
</blockquote></details>

Done.
___
*[`internal/source/kafka/consumer.go` line 69 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYgrkZ1y5sjmHEM35u:-Nxwg0hP2IEhC7I2d1_O:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/consumer.go#L69)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Not knowing how `Setup` is called, and from which goroutine(s), you should go ahead and lock the mutex to avoid any surprises later on.
</blockquote></details>

Done.
___
*[`internal/source/kafka/consumer.go` line 110 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYhD_R8YcUkM3IA_j1:-Nxwg31a3YNTXF4O9yFg:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/consumer.go#L110)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Use `log.WithError(err).Error("message")` Otherwise, the error object isn't going to be presented to the logging hooks as an `error` object.
</blockquote></details>

Done.
___
*[`internal/source/kafka/injector.go` line 27 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYhjxz9urGFVEffgO8:-Nxwg4r7-RCjoYoA3_Y4:b-dojpzh) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/injector.go#L27)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Did you run `crlfmt`?  I think you'd get a code-quality warning if the imports aren't sorted.

`go run github.com/cockroachdb/crlfmt -w -ignore _gen.go .`
</blockquote></details>

it seems to me that they are properly sorted.
___
*[`internal/source/kafka/injector.go` line 53 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYhf1R-S-fHYSVCvTP:-NxwgD3oEGBnWrTXAYVV:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/injector.go#L53)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Alphabetize.
</blockquote></details>

Done.
___
*[`internal/source/kafka/provider.go` line 30 at r6](https://reviewable.io/reviews/cockroachdb/replicator/843#-NxYi0aW4arZJD9M5MpQ:-NxwgDvFBmc8_8I14Xy5:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/de7bf09de6f4bad44c5364a69a75f08ab5b1936b/internal/source/kafka/provider.go#L30)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort.
</blockquote></details>

Done.

**Review by bobvawter — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/843#-:-Ny2XiYa1GjEYrXIwwkI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @BramGruneir and @sravotto)

___
*[`internal/source/kafka/conn_test.go` line 40 at r7](https://reviewable.io/reviews/cockroachdb/replicator/843#-Ny2XDhi3cK-NfKCf4gR:-Ny2XDhjBA-s83gz8OV2:b-80xfat) ([raw file](https://github.com/cockroachdb/replicator/blob/c569c3aad36b9a85f3fae984e9e43e976b81e7a0/internal/source/kafka/conn_test.go#L40)):*
> ```Go
> 		done       bool
> 		timestamps ident.Map[hlc.Time]
> 		ensure     ident.Map[bool]
> ```

Sort.

**Review by sravotto — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/843#-:-Ny34IQA4NV0o7FPPIo5:b-ucfknh)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @bobvawter and @BramGruneir)

___
*[`internal/source/kafka/conn_test.go` line 40 at r7](https://reviewable.io/reviews/cockroachdb/replicator/843#-Ny2XDhi3cK-NfKCf4gR:-Ny34HKDBS3MsAZpbKJ6:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/c569c3aad36b9a85f3fae984e9e43e976b81e7a0/internal/source/kafka/conn_test.go#L40)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort.
</blockquote></details>

Done.

**Pull request merged**
