### PR TITLE
load: Populate sparse rows from target tables

### LINKED ISSUE #705: Support loading records from target tables
We have the `apply` package for modifying a target table, but there's no way to load a row into a mutation. This would be a nice-to-have feature in the userscript, as it would allow the `TargetTX` interface to be able to load a value by PK. This enables a soft-delete use case that doesn't require the changefeed to be created with the `diff` option.

### PR DESCRIPTION
**Pull request by bobvawter**
This change adds a new target-database API for retrieving rows from a target table. The Loader accepts a slice of partially-populated property bags and retrieves the missing properties from the target database.

Fixes #705

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/937)

### CODE REVIEW

**Review by sravotto — APPROVED** [review]
:lgtm: - We should rework the toasted column to use this. I think we just need to drop the toasted column when we receive it, so we get the value from the target db, 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/937#-:-O2ACSvfAYXGWM2Xy0P4:b-6fmz9k)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @BramGruneir)

**Comment by bobvawter** [comment]
PTAL at the latest revision, I found a workaround for the MariaDB join not matching.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 11 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/937#-:-O2WBRZR-EpkZRQ4Hmnt:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @bobvawter)

___
*[`internal/target/load/load.go` line 84 at r2](https://reviewable.io/reviews/cockroachdb/replicator/937#-O2W1GxNEdVOxZrRE4tf:-O2W1GxNEdVOxZrRE4tg:b-tmkhzr) ([raw file](https://github.com/cockroachdb/replicator/blob/9fb8acfe96db5fa1aef1c94bd9f5f640c9d93c5d/internal/target/load/load.go#L84)):*
> ```Go
> // populate them from the target table.
> //
> // This method updates the property
> ```

nit: spacing
___
*[`internal/target/load/queries/my.tmpl` line 1 at r2](https://reviewable.io/reviews/cockroachdb/replicator/937#-O2W9fME7spxY6lfWPVs:-O2W9fMF4gxbPbYBlhCc:bnfrw5d) ([raw file](https://github.com/cockroachdb/replicator/blob/9fb8acfe96db5fa1aef1c94bd9f5f640c9d93c5d/internal/target/load/queries/my.tmpl#L1)):*
> ```
> {{- /*gotype: github.com/cockroachdb/replicator/internal/target/load.demand*/ -}}
> ```

Does it make sense to just have another entry for MariaDB instead of adding the logic into the template?
___
*[`internal/util/merge/bag.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/replicator/937#-O2WA9Im2ELA7K0Jmj_n:-O2WA9Im2ELA7K0Jmj_o:bhx873o) ([raw file](https://github.com/cockroachdb/replicator/blob/9fb8acfe96db5fa1aef1c94bd9f5f640c9d93c5d/internal/util/merge/bag.go#L147)):*
> ```Go
> // Entry returns the mapped Entry, or returns false.
> func (b *Bag) Entry(key ident.Ident) (_ *Entry, ok bool) {
> 	key = b.renamed(key)
> ```

renamedKey?

Or perhaps just one line?
`return b.Mapped.Get(b.renamed(key))`
___
*[`internal/util/workload/base.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/replicator/937#-O2WAaWo2S1RzYpgEEve:-O2WAaWo2S1RzYpgEEvf:b8sr85) ([raw file](https://github.com/cockroachdb/replicator/blob/9fb8acfe96db5fa1aef1c94bd9f5f640c9d93c5d/internal/util/workload/base.go#L43)):*
> ```Go
> }
> 
> // A ParentRow contains an expected snapshot of some parent table row.
> ```

Why not just combine parent and child?

This smells like a tree.

**Review by bobvawter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/937)* status: 11 of 16 files reviewed, 3 unresolved discussions (waiting on @BramGruneir)

___
*[`internal/target/load/load.go` line 84 at r2](https://reviewable.io/reviews/cockroachdb/replicator/937#-O2W1GxNEdVOxZrRE4tf:-O2_Bjrw0y46Kss3J_Qp:bt2vr1b) ([raw file](https://github.com/cockroachdb/replicator/blob/9fb8acfe96db5fa1aef1c94bd9f5f640c9d93c5d/internal/target/load/load.go#L84)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nit: spacing
</blockquote></details>

Fixed.
___
*[`internal/target/load/queries/my.tmpl` line 1 at r2](https://reviewable.io/reviews/cockroachdb/replicator/937#-O2W9fME7spxY6lfWPVs:-O2eY2G1EfaSdHE14lwk:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/9fb8acfe96db5fa1aef1c94bd9f5f640c9d93c5d/internal/target/load/queries/my.tmpl#L1)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Does it make sense to just have another entry for MariaDB instead of adding the logic into the template?
</blockquote></details>

Done.
___
*[`internal/util/merge/bag.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/replicator/937#-O2WA9Im2ELA7K0Jmj_n:-O2eYCbA75kZPr1god0f:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/9fb8acfe96db5fa1aef1c94bd9f5f640c9d93c5d/internal/util/merge/bag.go#L147)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

renamedKey?

Or perhaps just one line?
`return b.Mapped.Get(b.renamed(key))`
</blockquote></details>

Done.
___
*[`internal/util/workload/base.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/replicator/937#-O2WAaWo2S1RzYpgEEve:-O2_BH9F-DKw_yrplBAQ:b-o5vo6g) ([raw file](https://github.com/cockroachdb/replicator/blob/9fb8acfe96db5fa1aef1c94bd9f5f640c9d93c5d/internal/util/workload/base.go#L43)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not just combine parent and child?

This smells like a tree.
</blockquote></details>

It is a tree, albeit one expressed in a relational database schema.  These two types are intended to convey the data as it should exist in the table row.  You wouldn't use them for actual processing.

**Pull request merged**
