### PR TITLE
stage: Add a configuration object to the stage package.

### PR DESCRIPTION
**Pull request by bobvawter**
This change brings the stage package in line with other packages that provide a configuration object and flag bindings.  Several timing and sizing values around the consistency chack are added to make it less intensive on larger deployments.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1053)

### CODE REVIEW

**Review by ryanluu12345 — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1053)* status: all files reviewed, 2 unresolved discussions (waiting on @bobvawter, @BramGruneir, and @sravotto)

___
*[`internal/staging/stage/config.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/replicator/1053#-O9zg-ehD496n4dDCIpg:-O9zg-ehD496n4dDCIph:b4apma4) ([raw file](https://github.com/cockroachdb/replicator/blob/c289ec9f30e7843eaf562cae9bb77f7401a1803b/internal/staging/stage/config.go#L27)):*
> ```Go
> const (
> 	defaultMarkAppliedBatchSize = 100_000
> 	defaultSanityCheckPeriod    = 10 * time.Minute
> ```

Previously, if I'm not mistaken the sanity check period was 1 minute. How did we arrive at this value that is 10x less frequent? Since the implication is that alerts can fire later for inconsistent data, wondering what potential window of inconsistency is acceptable for customers.

Although, since it's configurable now, customers can just set the value they deem appropriate.
___
*[`internal/staging/stage/stage.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/replicator/1053#-O9zh4WT-xF-eOmlFqPX:-O9zh4WT-xF-eOmlFqPY:bxtmy82) ([raw file](https://github.com/cockroachdb/replicator/blob/c289ec9f30e7843eaf562cae9bb77f7401a1803b/internal/staging/stage/stage.go#L196)):*
> ```Go
> 	// Report unapplied mutations on a periodic basis.
> 	ctx.Go(func(ctx *stopper.Context) error {
> 		if f.cfg.UnappliedPeriod <= 0 {
> ```

Just to clarify, if any of these configurations are lte 0, we just disable this check right?

**Review by bobvawter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1053)* status: all files reviewed, 2 unresolved discussions (waiting on @BramGruneir, @ryanluu12345, and @sravotto)

___
*[`internal/staging/stage/config.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/replicator/1053#-O9zg-ehD496n4dDCIpg:-O9zu0FX9lf0ITLs4Ksl:b7zua1r) ([raw file](https://github.com/cockroachdb/replicator/blob/c289ec9f30e7843eaf562cae9bb77f7401a1803b/internal/staging/stage/config.go#L27)):*
<details><summary><i>Previously, ryanluu12345 wrote…</i></summary><blockquote>

Previously, if I'm not mistaken the sanity check period was 1 minute. How did we arrive at this value that is 10x less frequent? Since the implication is that alerts can fire later for inconsistent data, wondering what potential window of inconsistency is acceptable for customers.

Although, since it's configurable now, customers can just set the value they deem appropriate.
</blockquote></details>

All defaults are wrong for somebody.  This query turns out to be much heavier weight than anticipated, so reducing the frequency seemed like a good idea.
___
*[`internal/staging/stage/stage.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/replicator/1053#-O9zh4WT-xF-eOmlFqPX:-O9ztzvnCMWkgFQ0jmeJ:btqqu5l) ([raw file](https://github.com/cockroachdb/replicator/blob/c289ec9f30e7843eaf562cae9bb77f7401a1803b/internal/staging/stage/stage.go#L196)):*
<details><summary><i>Previously, ryanluu12345 wrote…</i></summary><blockquote>

Just to clarify, if any of these configurations are lte 0, we just disable this check right?
</blockquote></details>

Correct.

**Comment by ryanluu12345** [comment]
This resolves #1051

**Review by ryanluu12345 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1053)* status: all files reviewed, 1 unresolved discussion (waiting on @bobvawter, @BramGruneir, and @sravotto)

___
*[`internal/staging/stage/config.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/replicator/1053#-O9zg-ehD496n4dDCIpg:-OA-URex33rtw6pcm6GC:be08et8) ([raw file](https://github.com/cockroachdb/replicator/blob/c289ec9f30e7843eaf562cae9bb77f7401a1803b/internal/staging/stage/config.go#L27)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

All defaults are wrong for somebody.  This query turns out to be much heavier weight than anticipated, so reducing the frequency seemed like a good idea.
</blockquote></details>

Yep, agreed that we should reduce the frequency. Well, it's configurable, so no concerns here.

**Pull request merged**
