### PR TITLE
objstore: initial implementation

### PR DESCRIPTION
**Pull request by sravotto**
This change adds a connector for changefeeds persisted within an object storage provider. It is currently limited to S3 and local storage.

The initial implementation uses a single replicator process that fetches files from the object store, parses the mutations and applies them using the Convoyer interface.

It assumes that at any given time, if the files are iterated in lexicographic filename order, then encountering any filename containing `RESOLVED`  means that everything before it is finalized.
Based on this, it finds two consecutive `RESOLVED` files in lexicographic order, and it processes all the files between the `RESOLVED` files.

It uses a simple exponential backoff strategy to retry transient errors that we might encounter when interacting with the object store.

This change also adds mock implementations of bucket.Bucket and eventproc.Processor to help in testing.

Integration testing will be provided in a following PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/905)

### CODE REVIEW

**Review by sravotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/905)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

___
*[`internal/source/objstore/config.go` line 166 at r1](https://reviewable.io/reviews/cockroachdb/replicator/905#gh-1631673560:-NzoV9-9AxfZwZQoApyA:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/78c22938d210085b8623161e420c6fddcdffea8e/internal/source/objstore/config.go#L166)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Clear-text logging of sensitive information

[Sensitive data returned by an access to SecretKey](1) flows to a logging call.

[Show more details](https://github.com/cockroachdb/replicator/security/code-scanning/22)
</blockquote></details>

Done.

**Review by bobvawter — CHANGES_REQUESTED** [review]
> Reviewed 5 of 26 files at r1, 1 of 5 files at r2, 23 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/905)* status: 29 of 31 files reviewed, 25 unresolved discussions (waiting on @BramGruneir, @github-advanced-security[bot], and @sravotto)

___
*[`internal/sinktest/mocks/collector.go` line 42 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qFFCWDCPaLyOeLK9S:-O-qFFCWDCPaLyOeLK9T:b-z4lg97) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/sinktest/mocks/collector.go#L42)):*
> ```Go
> func NewCollector(capacity int) *Collector {
> 	return &Collector{
> 		mu: struct {
> ```

This is an awkward syntax.

```
c := &Collector{}
c.mu.batch = make(...)
return c
```
___
*[`internal/sinktest/mocks/collector.go` line 56 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qFP9B4x4iyOImHGOn:-O-qFP9B4x4iyOImHGOo:b-fx9cmn) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/sinktest/mocks/collector.go#L56)):*
> ```Go
> 	defer c.mu.Unlock()
> 	slices.Sort(c.mu.batch)
> 	return c.mu.batch
> ```

This exposes the backing array to external callers, leading to potentially-unsynchronized behavior. A method like this would typically return a new slice.
___
*[`internal/source/objstore/config.go` line 44 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-bYS1675eJwuoOqyrn:-O-bYS1675eJwuoOqyro:bll0ag) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L44)):*
> ```Go
> 	defaultBufferSize           = bufio.MaxScanTokenSize // 64K
> 	defaultFetchDelay           = 100 * time.Millisecond
> 	defaultNumberOfWorkers      = runtime.NumCPU()
> ```

This should be based on GOMAXPROCS instead, which defaults to the number of CPUs, and can be adjusted by the operator.
___
*[`internal/source/objstore/config.go` line 63 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q2jC2C9LJ9iGEYALm:-O-q2jC3-tnwfnIIPuaR:b-cndr29) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L63)):*
> ```Go
> 	S3Storage
> 	// UnknownStorage identifies other storage not currently supported.
> 	UnknownStorage
> ```

"Unknown" enum entries are typically `iota`. This makes the zero value of the enum type more useful.
___
*[`internal/source/objstore/config.go` line 66 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qDsuj2QEtpHiYa-QX:-O-qDsuj2QEtpHiYa-QY:bxwu24d) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L66)):*
> ```Go
> )
> 
> //go:generate go run golang.org/x/tools/cmd/stringer -type=Provider
> ```

Move this closer to the `type Provider` line.
___
*[`internal/source/objstore/config.go` line 69 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q36kDB7m4Ne0TV9i5:-O-q36kDB7m4Ne0TV9i6:bj2bylu) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L69)):*
> ```Go
> var (
> 	Providers = map[string]Provider{
> 		"file": LocalStorage,
> ```

Are these map entries intended to be an inversion of the `Provider.String()` method? If not, clarify the kind of value in the map key.  Also, you don't need a multi-variable declaration block here, since there's only the one var.
___
*[`internal/source/objstore/config.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qFsNuDiEuPeWbwv_I:-O-qFsNv8JR66Jpixfgq:b-80xfat) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L82)):*
> ```Go
> 	Sequencer sequencer.Config
> 	Staging   sinkprod.StagingConfig
> 	TLS       secure.Config
> ```

Sort.
___
*[`internal/source/objstore/config.go` line 107 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q3M5NEM-kl_a0LlX_:-O-q3M5OEg413a8pBY78:bwvshoo) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L107)):*
> ```Go
> 	c.Sequencer.Bind(f)
> 	c.Staging.Bind(f)
> 	c.Target.Bind(f)
> ```

Is this missing TLS?

I've been wanting to write a config code-generator to make it less error-prone to compose all the different config types we're accumulating.
___
*[`internal/source/objstore/config.go` line 140 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q3XDu2yoGwjXthnV0:-O-q3XDu2yoGwjXthnV1:bb7447d) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L140)):*
> ```Go
> 		return err
> 	}
> 	if err := c.Target.Preflight(); err != nil {
> ```

TLS?
___
*[`internal/source/objstore/config.go` line 149 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q3_411riedEK2uqeg:-O-q3_411riedEK2uqeh:b-2k5t29) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L149)):*
> ```Go
> }
> 
> func (c *Config) preflight(_ context.Context) error {
> ```

Is this private method called from anywhere else?  Also, why does it have the context argument.
___
*[`internal/source/objstore/config.go` line 156 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q5g-vCu3L3uqzt9o-:-O-q5g-wAEttc-I-gfaH:b-3vv120) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L156)):*
> ```Go
> 	// Extract provider configuration from the storage URL
> 	c.bucketName = strings.TrimPrefix(u.Path, "/")
> 	switch Providers[u.Scheme] {
> ```

`default` case that returns an error for an unmatched scheme?
___
*[`internal/source/objstore/conn.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q6N3t4j--bN3Z9pen:-O-q6N3t4j--bN3Z9peo:b-qw37o2) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L70)):*
> ```Go
> 	ctx.Go(func(ctx *stopper.Context) error {
> 		c.leases.Singleton(ctx,
> 			fmt.Sprintf("%s.objstore.scan", c.config.bucketName),
> ```

Should this be a log statement?
___
*[`internal/source/objstore/conn.go` line 102 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-bZlvw8NXhECzGotY3:-O-bZlvw8NXhECzGotY4:b-h8gd2k) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L102)):*
> ```Go
> // deleted, included in hive queries, etc). A typical user of cloudStorageSink
> // would periodically do exactly this.
> // (see https://github.com/asg0451/cockroach/blob/75fb68babf8e4392eee8fe4dc150299c22dc7962/pkg/ccl/changefeedccl/sink_cloudstorage.go#L112)
> ```

Why is this pointing at somebody else's repo?
___
*[`internal/source/objstore/conn.go` line 149 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-b_OsB1SA4nC7fyo00:-O-b_OsB1SA4nC7fyo01:b3t1j0f) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L149)):*
> ```Go
> 		// This shouldn't happen.
> 		log.WithField("bucket", c.config.bucketName).Warnf("got an empty range")
> 		return nil
> ```

If it shouldn't happen, shouldn't this return an error?
___
*[`internal/source/objstore/conn.go` line 263 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q7Lpa84IYK0P-UIZT:-O-q7Lpa84IYK0P-UIZU:b-6yphqm) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L263)):*
> ```Go
> 					count++
> 					select {
> 					case <-ctx.Stopping():
> ```

Use `IsStopping()` here since there's only the single channel you're inspecting.
___
*[`internal/source/objstore/conn.go` line 272 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q7Wxs3XSrYri1K5Ot:-O-q7Wxs3XSrYri1K5Ou:b3ks857) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L272)):*
> ```Go
> 		err := c.retry(operation, "find resolved")
> 		if err != nil {
> 			log.WithField("bucket", c.config.bucketName).
> ```

Use `WithError()` to improve logging.
___
*[`internal/source/objstore/conn.go` line 306 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q8_nD8CO5zOiQ-RvD:-O-q8_nD8CO5zOiQ-RvE:b-qivkd) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L306)):*
> ```Go
> 		g.Go(func() error {
> 			start := time.Now()
> 			err := c.retry(operation, fmt.Sprintf("processing %s", file))
> ```

This should either be `errors.Wrapf()` or `fmt.Errorf()` using the `%w` verb.
___
*[`internal/source/objstore/conveyor.go` line 28 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-baQhp7mQrIT3pnWsw:-O-baQhp7mQrIT3pnWsx:bvbe4vy) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conveyor.go#L28)):*
> ```Go
> )
> 
> // Conveyor exposes the methods used by the kafka connector to deliver
> ```

Kafka?
___
*[`internal/source/objstore/metrics.go` line 30 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qGx2mA2tbUVFZHQJG:-O-qGx2mA2tbUVFZHQJH:b-i8h1hx) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/metrics.go#L30)):*
> ```Go
> var (
> 	applyDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
> 		Name:    "objstore_apply_seconds",
> ```

Metrics that measure how long an activity took are named `xyz_duration_seconds` elsewhere in the code base.
___
*[`internal/source/objstore/metrics.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qBlN7AthF-mjIjy95:-O-qBlN7AthF-mjIjy96:bdchg9b) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/metrics.go#L34)):*
> ```Go
> 		Buckets: metrics.LatencyBuckets,
> 	}, topicLabels)
> 	batchSize = promauto.NewGaugeVec(prometheus.GaugeOpts{
> ```

I think this should be either a histogram or a counter. A gauge is going to just read out the most recent value, so it loses all history between metrics samples.
___
*[`internal/source/objstore/provider.go` line 51 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qCgruDSgKcsAWL6Ib:-O-qCgrv1jj9RC8eymxC:bdko3im) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/provider.go#L51)):*
> ```Go
> 
> // ProvideConveyorConfig is called by Wire.
> func ProvideConveyorConfig(cfg *Config) *conveyor.Config {
> ```

This could be listed in `wire.FieldsOf(new(*EagerConfig), "DLQ", "Sequencer", "Staging", "Target")` to reduce clutter.
___
*[`internal/source/objstore/provider.go` line 99 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qEdkK1GWQW7a00eVy:-O-qEdkK1GWQW7a00eVz:b-l4xs4t) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/provider.go#L99)):*
> ```Go
> 		state: state{
> 			memo: memo,
> 			key:  fmt.Sprintf("objstore_%s", config.bucketName),
> ```

Is the name of the bucket alone sufficiently unique?  It seems like this should be a URI instead.
___
*[`internal/source/objstore/state.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qF5ij1PkDmSy_bD4G:-O-qF5ij1PkDmSy_bD4H:b-suv37y) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/state.go#L29)):*
> ```Go
> type state struct {
> 	memo types.Memo
> 	key  string
> ```

Alphabetize.
___
*[`internal/source/objstore/state.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qDAxY8qteMgnpeLR-:-O-qDAxY8qteMgnpeLR0:busxse9) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/state.go#L45)):*
> ```Go
> 	value := valuePayload{}
> 	if v != nil {
> 		err = json.Unmarshal(v, &value)
> ```

How should the system behave if additional fields are added to the payload by subsequent versions of the code?  Consider instantiating a `json.Decoder` and disallowing unknown fields to avoid information loss in the future.

**Review by sravotto — COMMENTED** [review]
Please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/905#-:-O-rgm0A3vD-JvJMuk-g:b1xog4q)* status: 18 of 31 files reviewed, 25 unresolved discussions (waiting on @bobvawter, @BramGruneir, and @github-advanced-security[bot])

___
*[`internal/sinktest/mocks/collector.go` line 42 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qFFCWDCPaLyOeLK9S:-O-r_Ogg60sO1YZdB2Hl:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/sinktest/mocks/collector.go#L42)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This is an awkward syntax.

```
c := &Collector{}
c.mu.batch = make(...)
return c
```
</blockquote></details>

Done.
___
*[`internal/sinktest/mocks/collector.go` line 56 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qFP9B4x4iyOImHGOn:-O-r_Rbx1PlXLt7ssqjf:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/sinktest/mocks/collector.go#L56)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This exposes the backing array to external callers, leading to potentially-unsynchronized behavior. A method like this would typically return a new slice.
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 44 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-bYS1675eJwuoOqyrn:-O-r_T--DjoIQB-o8H_J:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L44)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This should be based on GOMAXPROCS instead, which defaults to the number of CPUs, and can be adjusted by the operator.
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 63 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q2jC2C9LJ9iGEYALm:-O-r_TyDAtJQMCbZ-mdQ:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L63)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

"Unknown" enum entries are typically `iota`. This makes the zero value of the enum type more useful.
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 66 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qDsuj2QEtpHiYa-QX:-O-r_YKeBA5gDbEgANXv:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L66)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Move this closer to the `type Provider` line.
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 69 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q36kDB7m4Ne0TV9i5:-O-r_cqX6UcuNKGJqIys:b-q9lx7b) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L69)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Are these map entries intended to be an inversion of the `Provider.String()` method? If not, clarify the kind of value in the map key.  Also, you don't need a multi-variable declaration block here, since there's only the one var.
</blockquote></details>

adding comment.
___
*[`internal/source/objstore/config.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qFsNuDiEuPeWbwv_I:-O-r_fmXEFqoGp_rh6U6:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L82)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Sort.
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 107 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q3M5NEM-kl_a0LlX_:-O-r_gdl68USzLdrMsJA:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L107)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is this missing TLS?

I've been wanting to write a config code-generator to make it less error-prone to compose all the different config types we're accumulating.
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 140 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q3XDu2yoGwjXthnV0:-O-r_hCh0OksqSKoTXXW:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L140)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

TLS?
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 149 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q3_411riedEK2uqeg:-O-r_iJ1-0G9KgId6Qa-:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L149)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is this private method called from anywhere else?  Also, why does it have the context argument.
</blockquote></details>

Done.
___
*[`internal/source/objstore/config.go` line 156 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q5g-vCu3L3uqzt9o-:-O-r_jI64c8pVdWpCEbu:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/config.go#L156)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`default` case that returns an error for an unmatched scheme?
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q6N3t4j--bN3Z9pen:-O-r_kJp2b1e3MhAIIhb:b-x2ibqv) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L70)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Should this be a log statement?
</blockquote></details>

It's the lease name. I added an explicit identifier in the config that I can use also for the memo.
___
*[`internal/source/objstore/conn.go` line 102 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-bZlvw8NXhECzGotY3:-O-r_uS7781bXc0I0AYt:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L102)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Why is this pointing at somebody else's repo?
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 149 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-b_OsB1SA4nC7fyo00:-O-r_vKZBcJcPUb2KqeG:b-4hbcoo) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L149)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

If it shouldn't happen, shouldn't this return an error?
</blockquote></details>

At worst, it's a no-op. But I wanted to log a warning, in case it would ever happen.
___
*[`internal/source/objstore/conn.go` line 263 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q7Lpa84IYK0P-UIZT:-O-ra5yO35l74JLQfgnK:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L263)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Use `IsStopping()` here since there's only the single channel you're inspecting.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 272 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q7Wxs3XSrYri1K5Ot:-O-ra71y8d5qARV3Ex41:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L272)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Use `WithError()` to improve logging.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conn.go` line 306 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-q8_nD8CO5zOiQ-RvD:-O-ra7yVDiUSkaXSBlBD:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conn.go#L306)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This should either be `errors.Wrapf()` or `fmt.Errorf()` using the `%w` verb.
</blockquote></details>

Done.
___
*[`internal/source/objstore/conveyor.go` line 28 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-baQhp7mQrIT3pnWsw:-O-ra8mW8Zh379Amjgs0:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/conveyor.go#L28)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Kafka?
</blockquote></details>

Done.
___
*[`internal/source/objstore/metrics.go` line 30 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qGx2mA2tbUVFZHQJG:-O-raAALEHXp_B2kFn-c:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/metrics.go#L30)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Metrics that measure how long an activity took are named `xyz_duration_seconds` elsewhere in the code base.
</blockquote></details>

Done.
___
*[`internal/source/objstore/metrics.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qBlN7AthF-mjIjy95:-O-raAnf06S3PTiNKaj-:b-diny2t) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/metrics.go#L34)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

I think this should be either a histogram or a counter. A gauge is going to just read out the most recent value, so it loses all history between metrics samples.
</blockquote></details>

yep. Done.
___
*[`internal/source/objstore/provider.go` line 51 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qCgruDSgKcsAWL6Ib:-O-rgcXi6mzxs5sk3w13:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/provider.go#L51)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This could be listed in `wire.FieldsOf(new(*EagerConfig), "DLQ", "Sequencer", "Staging", "Target")` to reduce clutter.
</blockquote></details>

Done.
___
*[`internal/source/objstore/provider.go` line 99 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qEdkK1GWQW7a00eVy:-O-raGGm687Nk8AMk8JM:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/provider.go#L99)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is the name of the bucket alone sufficiently unique?  It seems like this should be a URI instead.
</blockquote></details>

Done.
___
*[`internal/source/objstore/state.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qF5ij1PkDmSy_bD4G:-O-raK4K2ZQRro0xAj5-:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/state.go#L29)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Alphabetize.
</blockquote></details>

Done.
___
*[`internal/source/objstore/state.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qDAxY8qteMgnpeLR-:-O-raMHNElR3go8v-png:b-xj4w9e) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/state.go#L45)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

How should the system behave if additional fields are added to the payload by subsequent versions of the code?  Consider instantiating a `json.Decoder` and disallowing unknown fields to avoid information loss in the future.
</blockquote></details>

Is this what you mean?

**Review by bobvawter — APPROVED** [review]
:lgtm: w/nit

> Reviewed 1 of 26 files at r1, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/905#-:-O0B_iMK726P_JaUy00s:b-7v1hfy)* status: all files reviewed, 2 unresolved discussions (waiting on @BramGruneir, @github-advanced-security[bot], and @sravotto)

___
*[`internal/source/objstore/state.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qDAxY8qteMgnpeLR-:-O0B_WmVA5z2KG3Q5_A1:b-yn2yb6) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/state.go#L45)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Is this what you mean?
</blockquote></details>

Yes, but also call https://pkg.go.dev/encoding/json#Decoder.DisallowUnknownFields

**Review by sravotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/905)* status: 29 of 31 files reviewed, 2 unresolved discussions (waiting on @bobvawter, @BramGruneir, and @github-advanced-security[bot])

___
*[`internal/source/objstore/state.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/replicator/905#-O-qDAxY8qteMgnpeLR-:-O0EYFV25HagU_KuwNwU:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/2ac0feb57310d7e6f17934026c7a371c56439b24/internal/source/objstore/state.go#L45)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Yes, but also call https://pkg.go.dev/encoding/json#Decoder.DisallowUnknownFields
</blockquote></details>

Done.

**Pull request merged**
