### PR TITLE
Update Artifact action to v4

### PR DESCRIPTION
**Pull request by rail**
Fixes: DEVINF-1334

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1076)

### CODE REVIEW

**Comment by rail** [comment]
> Tests don't pass.

Ooooh, looks like they changed the action behavior.

**Comment by rail** [comment]
Looks like the name should be unique. We need to append something using `${{ matrix.xxx }}`. Any suggestions?

**Comment by Jeremyyang920** [comment]
> Looks like the name should be unique. We need to append something using `${{ matrix.xxx }}`. Any suggestions?

I don't have a real suggestion, Maybe whatever the source DB was but not sure if that ends up being unique right now. cc @ryanluu12345

**Comment by rail** [comment]
Hmm, actually this may be a bit more complicated. The download step should collect all uploaded artifacts. 🤔

**Comment by ryanluu12345** [comment]
> Hmm, actually this may be a bit more complicated. The download step should collect all uploaded artifacts. 🤔

Hi @rail , my apologies for the late reply here. I have some work this week that entails updating our CI for replicator. I'll look into making these changes so that we collect all uploaded artifacts together.

**Comment by rail** [comment]
No pressure, it's just at some point in December the old version is going to stop working. :)

**Comment by ryanluu12345** [comment]
Hi @rail , I just dug into this more closely and realized that we can probably take the approach outlined here: https://github.com/actions/upload-artifact

At a high level, we will need to do the following:
1. Upload with a unique artifact name => requires giving a unique identifier to these cases
2. Download with a "path" and "pattern" => requires updating the download artifact to use the "pattern" config
```
download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: my-artifact
        pattern: my-artifact-*
        merge-multiple: true
```
Let me go ahead and make a change for this. I'll probably just assign an ID to each of these test cases.

**Comment by ryanluu12345** [comment]
Closing in favor of: https://github.com/cockroachdb/replicator/pull/1086

**Pull request closed without merging**
